      SUBROUTINE GDF_OPTION(CHOPT,VALUE,IERR)
C
      USE GDF
C
      IMPLICIT NONE
C
      CHARACTER(*) CHOPT
      LOGICAL      VALUE
      INTEGER      IERR
C
      CALL GDF$OPTION(CHOPT,VALUE,IERR)
C
      END
C
      SUBROUTINE GDF_INIT(CHOPT,IERR)
C
      USE GDF
C
      CHARACTER(*) CHOPT
      INTEGER      IERR
C
      CALL GDF$INIT(CHOPT,IERR)
C
      END
C
      SUBROUTINE GDF_OPEN(UNIT,FILE,CHOPT,IERR)
C
      USE GDF
C
      INTEGER      UNIT
      CHARACTER(*) FILE
      CHARACTER(*) CHOPT
      INTEGER      IERR
C
      CALL GDF$OPEN(UNIT,FILE,CHOPT,IERR)
C
      END
C
      SUBROUTINE GDF_READ(UNIT,CHOPT,IERR)
C
      USE GDF
C
      INTEGER      UNIT
      CHARACTER(*) CHOPT
      INTEGER      IERR
C
      CALL GDF$READ(UNIT,CHOPT,IERR)
C
      END
C
      SUBROUTINE GDF_WRITE(UNIT,CHOPT,IERR)
C
      USE GDF
C
      INTEGER      UNIT
      CHARACTER(*) CHOPT
      INTEGER      IERR
C
      CALL GDF$WRITE(UNIT,CHOPT,IERR)
C
      END
C
      SUBROUTINE GDF_CLOSE(UNIT,IERR)
C
      USE GDF
C
      INTEGER UNIT
      INTEGER IERR
C
      CALL GDF$CLOSE(UNIT,IERR)
C
      END
C
      SUBROUTINE GDF_EXIT(IERR)
C
      USE GDF
C
      INTEGER IERR
C
      CALL GDF$EXIT(IERR)
C
      END
C
      SUBROUTINE GDF_PRINT_EVENT10(EVENT,IERR)
C
      USE GDF
C
      TYPE(GDF_EV10_T) :: EVENT
      INTEGER             IERR
C
      CALL GDF$PRINT_EVENT10(EVENT,IERR)
C
      END
C
      SUBROUTINE GDF_PRINT_FRAME10(FRAME,IERR)
C
      USE GDF
C
      TYPE(GDF_FR10_T) :: FRAME
      INTEGER             IERR
C
      CALL GDF$PRINT_FRAME10(FRAME,IERR)
C
      END
C
      SUBROUTINE GDF_PRINT_RUN(RUN,IERR)
C
      USE GDF
C
      TYPE(GDF_RUN_T) :: RUN
      INTEGER            IERR
C
      CALL GDF$PRINT_RUN(RUN,IERR)
C
      END
C
      SUBROUTINE GDF_PRINT_TRACK(TRACK,IERR)
C
      USE GDF
C
      TYPE(GDF_TRACK_T) :: TRACK
      INTEGER              IERR
C
      CALL GDF$PRINT_TRACK(TRACK,IERR)
C
      END
C
      SUBROUTINE GDF_PRINT_HV(HV,IERR)
C
      USE GDF
C
      TYPE(GDF_HV_T) :: HV
      INTEGER           IERR
C
      CALL GDF$PRINT_HV(HV,IERR)
C
      END
